# Generated by Django 3.1.7 on 2021-04-14 04:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 14, 4, 54, 14, 340206, tzinfo=utc)),
        ),
    ]
