# Generated by Django 3.1.7 on 2021-04-14 05:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 14, 5, 1, 3, 321425, tzinfo=utc)),
        ),
    ]
